name: SimplePrefixManager
version: '${project.version}'
main: me.mocha.simpleprefixmanager.SimplePrefixManager
api-version: '1.20'
commands:
  prefix:
    usage: /prefix (enable | disable | (custom prefix goes here))
    permission: SPM.prefix

